import React,{useEffect,useState} from 'react';
import {BrainCircuit,BriefcaseBusiness,Sparkles,UserRoundSearch} from 'lucide-react';
const API=import.meta.env.VITE_API_URL||'';
const demoResume='Full-stack engineer building React and Node.js applications with Express, MongoDB, Docker and REST APIs. Python machine learning experience with PyTorch and NLP.';
const demoJob='Looking for an AI + MERN engineer with React, Node.js, Express, MongoDB, Docker, Python, machine learning, NLP and AWS experience.';
export default function App(){
 const [f,setF]=useState({name:'Alex Morgan',email:'alex@example.com',resumeText:demoResume,jobDescription:demoJob});
 const [result,setResult]=useState(null); const [loading,setLoading]=useState(false); const [history,setHistory]=useState([]); const [err,setErr]=useState('');
 const load=()=>fetch(`${API}/api/candidates`).then(r=>r.json()).then(setHistory).catch(()=>{}); useEffect(load,[]);
 async function analyze(){setLoading(true);setErr('');try{const r=await fetch(`${API}/api/candidates/analyze`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(f)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');setResult(d.analysis);load()}catch(e){setErr(e.message)}finally{setLoading(false)}}
 return <div className="shell"><div className="topbar"><div className="brand"><span className="dot"/>HireSense AI</div><span className="badge">AI + MERN • Portfolio Build</span></div>
 <div className="hero"><div className="panel"><h1>Explainable AI recruiting, not black-box ranking.</h1><p className="sub">Semantic resume–job matching with skill-gap analysis, recruiter-friendly explanations, candidate history and a clean MERN dashboard.</p><div className="row"><span className="tag">FastEmbed</span><span className="tag">React</span><span className="tag">Express</span><span className="tag">MongoDB-ready</span></div></div>
 <div className="panel"><p className="section-title">Product signals</p><div className="kpis"><div className="kpi"><b>72%</b><span>semantic weighting</span></div><div className="kpi"><b>28%</b><span>skill coverage</span></div><div className="kpi"><b>100%</b><span>explainable</span></div></div></div></div>
 <div className="grid"><div className="panel"><p className="section-title"><UserRoundSearch size={15}/> Candidate analysis</p><div className="field"><label>Name</label><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></div><div className="field"><label>Resume text</label><textarea value={f.resumeText} onChange={e=>setF({...f,resumeText:e.target.value})}/></div><div className="field"><label>Job description</label><textarea value={f.jobDescription} onChange={e=>setF({...f,jobDescription:e.target.value})}/></div><button className="btn" onClick={analyze} disabled={loading}><Sparkles size={16}/>{loading?'Analyzing…':'Run AI match'}</button>{err&&<p className="alert">{err}</p>}</div>
 <div className="panel"><p className="section-title"><BrainCircuit size={15}/> AI decision</p>{result?<><div className="score">{result.score}%</div><div className="bar"><span style={{width:`${result.score}%`}}/></div><p className="muted">Semantic {result.semantic_similarity} • Skill coverage {result.skill_coverage}</p><h3>Matched skills</h3><div>{result.matched_skills?.map(x=><span className="tag" key={x}>{x}</span>)}</div><h3>Missing / growth areas</h3><div>{result.missing_skills?.map(x=><span className="tag" key={x}>{x}</span>)}</div><div className="cards" style={{marginTop:14}}>{result.explanation?.map((x,i)=><div className="card" key={i}>{x}</div>)}</div></>:<div className="muted">Run a match to see semantic alignment, skill coverage and rationale.</div>}</div></div>
 <div className="panel" style={{marginTop:18}}><p className="section-title"><BriefcaseBusiness size={15}/> Recent candidates</p><div className="list">{history.slice(0,5).map(c=><div className="item" key={c._id}><b>{c.name||'Candidate'}</b> <span className="badge">{c.analysis?.score||0}%</span><div className="muted">{c.analysis?.matched_skills?.slice(0,5).join(' • ')}</div></div>)}{!history.length&&<span className="muted">No saved candidates yet.</span>}</div></div><div className="footer">Built as an end-to-end AI product: UI → REST API → optional MongoDB → transformer inference.</div></div>}
